version: '3'
services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: your_username
      MONGO_INITDB_ROOT_PASSWORD: your_password
    ports:
      - "27017:27017"
